spring:
  boot:
    admin:
      url: http://localhost:9090
  application:
    name: Admin Server MS

# THIS EXAMPLE OF EMBEDDING A VIEW IS NOT WORKING YET - TAKEN FROM : https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/resources/application.yml
---
# tag::customization-external-views[]
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: ATLAS
            url: http://localhost:9090/atlas.html
            order: 2000
# end::customization-external-views[]
---
management:
  metrics:
    export:
      atlas:
        uri: http://localhost:7101/api/v1/publish
